GET http://localhost:8081/
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Request #1 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "Hello World", "received wrong text");
    });
%}

###

GET http://localhost:8081/books
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #2 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const books = [
            {
                "id": 1,
                "name": "mybook",
                "author": "me"
            },
            {
                "id": 2,
                "name": "yourbook",
                "author": "you"
            }
        ];
        client.assert(JSON.stringify(response.body) === JSON.stringify(books), "received wrong book")
    });
%}

###

GET http://localhost:8081/book/1
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #3 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 1,
            "name": "mybook",
            "author": "me"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}

###

GET http://localhost:8081/book/2
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #4 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 2,
            "name": "yourbook",
            "author": "you"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}

###

GET http://localhost:8081/book/1
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #5 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 1,
            "name": "mybook",
            "author": "me"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}

###

GET http://localhost:8081/book/2
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #6 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 2,
            "name": "yourbook",
            "author": "you"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}


###

PUT http://localhost:8081/book/1/update?name=Becoming&author=they
Authorization: Basic {{username}} {{password}}

> {%
    client.test("Request #7 is 200 ", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 1,
            "name": "Becoming",
            "author": "they"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}

###

GET http://localhost:8081/book/1
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #5 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 1,
            "name": "Becoming",
            "author": "they"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}


###
POST http://localhost:8081/book/1/invalidateCache
Authorization: Basic {{username}} {{password}}


###

GET http://localhost:8081/book/1
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #5 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 1,
            "name": "Becoming",
            "author": "they"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}


###
POST http://localhost:8081/books/invalidateCache
Authorization: Basic {{username}} {{password}}



###

GET http://localhost:8081/book/1
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #5 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 1,
            "name": "Becoming",
            "author": "they"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}


###

GET http://localhost:8081/book/2
Authorization: Basic {{username}} {{password}}


> {%
    client.test("Request #6 is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const book = {
            "id": 2,
            "name": "yourbook",
            "author": "you"
        };
        client.assert(JSON.stringify(response.body) === JSON.stringify(book), "received wrong book")
    });
%}
